# Timedata database
mysql:
  host: 127.0.0.1
  port: 3306
  user: kkkktest
  password: kkkktest
  database: kkkktest
# The help document URL you want to display.
help-document: "https://star-lin.feishu.cn/docs/doccnow2uz3RoK28RKLJleq0Qug"
# Delay (seconds) before server shutting down.
server-close-countdown: 10
# Cooldown (seconds) of /su commands.
su-command-cooldown: 2