name: StarlinUtils
version: 1.0.6
author: Katorly
main: com.github.katorly.starlinutils.StarlinUtils
api-version: 1.18
# softdepend:
#   - "ProtocolLib"
description: A Spigot plugin made for StarlinWorld.
commands:
  su:
    description: The main command of StarlinUtils.
    usage: /su
  givefly:
    description: Gives a specific player fly.
    usage: /givefly <player>
  listfly:
    description: Lists the players that have fly.
    usae: /listfly
  delfly:
    description: Removes a specific player fly.
    usage: /delfly <player>
